### ISSUE TITLE
Difference from ldp-app

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/LDPjs#2]
What is the difference of this app from https://github.com/OSLC/ldp-app? The READMEs look quite similar.

**Comment by jamsden** [comment]
There was some tight coupling between the sample application and the MongoDB implementation in how the data for the graphics was provided. This had to be removed or updated.

**Comment by berezovskyi** [comment]
But should we remove LDPjs app then?

**Comment by jamsden** [comment]
No, that has a valid sample LDP implementation using MongoDB. It just wasn't architecturally designed in a way that supported adaptors for different data sources.

**Comment by berezovskyi** [comment]
Well, ldp-app also requires mongo: https://github.com/OSLC/ldp-app#running

**Comment by jamsden** [comment]
Fixed.
